### ISSUE TITLE
Possible unreachable conjunction / disjunction refinement rules in the ANTLR grammar?

### ISSUE THREAD

**Issue by martingall87** [IHTSDO/snomed-expression-constraint-language#5]
Hi,

I've been investigating the SNOMED ECL ANTLR grammar for use with a language other than Java. Whilst experimenting with the ANTLR tooling, I've observed that the following rules may not be reachable in the grammar:
- `conjunctionrefinementset`
- `disjunctionrefinementset`

[Link to rules](https://github.com/IHTSDO/snomed-expression-constraint-language/blob/4347440bd1e2b8d23547819f088b417595670978/syntax/ECL.g4#L33C1-L35C63)

The `subrefinement` rule appears to be greedy in the `eclrefinement` rule they are used in. All conjunction / disjunction combinations I've tried seem to just use the `conjunctionattributeset`/`disjunctionattributeset` rules.

Example below using the latest ANTLR grammar in [ANTLR Lab](http://lab.antlr.org):

**ECL:**
```
<  404684003 |Clinical finding| :
          363698007 |Finding site|  = <<  39057004 |Pulmonary valve structure|  AND
          116676008 |Associated morphology|  = <<  415582006 |Stenosis|  AND
          42752001 |Due to|  = <<  445238008 |Malignant carcinoid tumor|
```

**Parse Hierarchy:**
<img width="432" alt="image" src="https://github.com/IHTSDO/snomed-expression-constraint-language/assets/101289520/c9dc2f42-32e8-413a-b731-efe2adda93de">

Are there scenarios that do use these two rules or could the grammar be simplified?

**Comment by kaicode** [comment]
Hi @martingall87, thanks for the question.
The `conjunctionrefinementset` and `disjunctionrefinementset` elements are only needed when using conjunction or disjunction with attribute groups, these use curly braces `{ }`. 

For example:
```
* : * = *, { * = * }
```
Or something like:
```
< 131148009 |Bleeding (finding)| : 
     { 363698007 |Finding site (attribute)| = << 422897007 |Vascular structure of stomach (body structure)|, 
       116676008 |Associated morphology (attribute)| = 50960005 |Hemorrhage (morphologic abnormality)| },
      42752001 |Due to (attribute)| = << 312131008 |Viral infection of the digestive tract (disorder)|
```

If no attribute groups are needed then I think you are correct that the `conjunctionrefinementset` element will not be used.

I hope that helps.
See [ECL Guide Attribute Groups](https://confluence.ihtsdotools.org/display/DOCECL/6.2+Refinements#id-6.2Refinements-AttributeGroups)

**Comment by martingall87** [comment]
Thank you so much for your reply @kaicode. Apologies I completely missed the dependency on the Attribute Groups so that makes sense!

**Comment by kaicode** [comment]
No worries at all, I'm glad you asked. It was good to check!
Cheers.
